receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: flux_commit_tracker

  otlp/jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/mimir:
    endpoint: mimir:9009
    tls:
      insecure: true
      insecure_skip_verify: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/mimir, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki, debug]
