# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'otel-collector'

  - job_name: 'flux-commit-tracker'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'flux-commit-tracker'
