apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: mimir
      streamingEnabled:
        metrics: true
        search: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
        query: "{{$__tags}} | trace_id=\"${__span.traceID}\" | span_id=\"${__span.spanID}\""
        spanEndTimeShift: 1s
        spanStartTimeShift: "-1s"
        tags:
          - key: service.name
            value: service_name

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id"
          matcherType: label
          name: "Trace ID"
          url: "${__value.raw}"

  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    uid: mimir
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      prometheusType: Mimir
